### ISSUE TITLE
iOS8 Rotation issue

### ISSUE THREAD

**Issue by Boyeen** [mutualmobile/MMProgressHUD#30]
Seem to have a problem with landscape orientation in iOS8. The progress view is always in portrait.

**Comment by jeremymedford** [comment]
I just updated our Podfile to use 0.3.0. Doing clean installs of Debug builds on iOS8.1 in the simulator and on an iPad Mini Retina still exhibit the issue.
It is definitely happening with the following call:
```
MMProgressHUD showWithTitle:
```

**Comment by vincentjames501** [comment]
+1. This is still an issue. While my PR is a hack, it does seem to work (at least for me).

**Comment by larsacus** [comment]
It would help very much if someone who is experiencing the issue to try and debug what specifically the problem is. As it stands, I currently cannot reproduce issues with rotation like everyone is describing on the latest code from the master branch using the example app in the `Demo/` folder. Some questions I have for everyone having issues:

1. Is this on all versions of iOS 8 (iOS 8, iOS 8.1, etc)?
2. Is the deployment target for your app iOS 7+, or is it iOS 8-only?
3. Are you using UIViewController-based status bar methods?
4. Are you using UIViewController-based rotation methods?
5. What exactly does it do when it "doesn't work"? Does it not rotate at all, does it rotate, but look broken, etc?

Like I said, I cannot reproduce this issue anymore, which makes it extremely difficult to fix.

**Comment by vincentjames501** [comment]
Here are some images and a description from our QA team's bug report:
On the current iOS staging build on iPhone 6 and 6+ if you tap to record audio while composing a message in landscape the audio record icon shows up incorrectly and if you rotate to portrait it does not correct itself.

Opening in portrait the audio icon is orientated appropriately but if you switch to landscape it gets out of whack.

See attached images for examples.

http://imgur.com/a/rDR42

Is this on all versions of iOS 8 (iOS 8, iOS 8.1, etc)?
iOS 8+
Is the deployment target for your app iOS 7+, or is it iOS 8-only?
iOS 7+
Are you using UIViewController-based status bar methods?
No
Are you using UIViewController-based rotation methods?
No
What exactly does it do when it "doesn't work"? Does it not rotate at all, does it rotate, but look broken, etc?
See description above

**Comment by jeremymedford** [comment]
Is this on all versions of iOS 8 (iOS 8, iOS 8.1, etc)?
iPad Mini w/ 8.1.2: YES
iPad simulators with 8.1: YES
Is the deployment target for your app iOS 7+, or is it iOS 8-only?
Deployment Target of 7.0.
Are you using UIViewController-based status bar methods?
No
Are you using UIViewController-based rotation methods?
No
What exactly does it do when it "doesn't work"? Does it not rotate at all, does it rotate, but look broken, etc?
We initiate the display of it and it remains in the incorrect orientation through out the duration of it being displayed. 
When the device is in any orientation besides the default portrait mode, it is always aligned with the default portrait mode. I've attached to images. One in landscape and one in 'upside-down' or reverse portrait mode.
![img_0022](https://cloud.githubusercontent.com/assets/2266909/5949206/4115ebda-a700-11e4-9d82-c3d547619e6c.jpg)
![img_0021](https://cloud.githubusercontent.com/assets/2266909/5949207/413a2978-a700-11e4-8444-a33d542ea33f.jpg)

**Comment by jeremymedford** [comment]
If it helps, at the time this was presented from LoginContainerViewController, this is the hierarchy:
```
<SplashViewController 0x7ae3d240>, state: disappeared, view: <UIView 0x7be91a70> not in the window
   + <LoginContainerViewController 0x7bea67a0>, state: appeared, view: <UIView 0x7bea7f90>, presented with: <_UIFullscreenPresentationController 0x7bea6d80>
   |    | <LoginViewController 0x7b86b850>, state: appeared, view: <UIView 0x7bead6b0>
   |    | <SelectMerchantViewController 0x7beaa360>, state: appeared, view: <UITableView 0x7c2dee00>
```

**Comment by joolskii** [comment]
Hi, 

I've just updated to version 3.0.0, and I'm hitting this issue too.

My application uses UIInterfaceOrientationLandscapeRight and UIInterfaceOrientationLandscapeLeft orientations only, however I've found that the MMProgressHUDWindow is being oriented incorrectly.

Looking at - (void)orientRootViewControllerForOrientation:(UIInterfaceOrientation)interfaceOrientation on MMProgressHUDWindow I've checked that the interfaceOrientation being passed is correct however, the applied transform is orienting the window incorrectly.

I've fixed my code for the moment by simply using a transform of 0, but I suspect this is not the complete solution.

--J

**Comment by btelintelo** [comment]
We are having this issue also.  iOS 8 with a deployment target of 7.1.  We managed to pull down the source for 2.3, fix the rotation issue, but now we are seeing a problem with the progress spinniner not dismissing properly sometimes and locking up the app.  v 0.30 is still broken.

**Comment by larsacus** [comment]
Is anyone on this thread having issues with rotation on i_Phone_, or is it only on iPad that this issue manifests itself?

**Comment by larsacus** [comment]
And as a follow-up can anyone reproduce this issue using the sample project included in this repo?

**Comment by larsacus** [comment]
I just pushed up 0.3.1 to CocoaPods. This has some other fixes, but there was one commit related to rotation that might actually fix what everyone is talking about in here and might be why I have not been able to reproduce this issue. If this is true, this is my bad for not pushing a release with that one commit in it prior to this.

Please try 0.3.1 out, let me know how it works out, and have an awesome weekend, everyone! :beers:
